# Generated by Django 5.2.18 on 2026-10-09 17:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'O CNPJ deve ter 14 dígitos, sem pontos ou barras.')], verbose_name='CNPJ')),
                ('razao_social', models.CharField(blank=True, max_length=255, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='nome fantasia')),
                ('cnae_principal', models.CharField(blank=True, db_index=True, max_length=7, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'O CNAE deve ter 7 dígitos, sem pontos ou barras.')], verbose_name='CNAE principal')),
                ('cnaes_secundarios', models.JSONField(blank=True, default=list, verbose_name='CNAEs secundários')),
                ('natureza_juridica', models.CharField(blank=True, max_length=4, verbose_name='natureza jurídica')),
                ('porte', models.CharField(blank=True, choices=[('00', 'Não informado'), ('01', 'Microempresa (ME)'), ('03', 'Empresa de Pequeno Porte (EPP)'), ('05', 'Demais')], max_length=2)),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='capital social')),
                ('data_abertura', models.DateField(blank=True, null=True, verbose_name='data de abertura')),
                ('situacao_cadastral', models.CharField(blank=True, choices=[('01', 'Nula'), ('02', 'Ativa'), ('03', 'Suspensa'), ('04', 'Inapta'), ('08', 'Baixada')], max_length=2, verbose_name='situação cadastral')),
                ('opcao_simples', models.BooleanField(blank=True, null=True, verbose_name='optante pelo Simples')),
                ('opcao_mei', models.BooleanField(blank=True, null=True, verbose_name='MEI')),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, db_index=True, max_length=100)),
                ('cep', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'O CEP deve ter 8 dígitos, sem traço.')], verbose_name='CEP')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='município')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('site', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distancia_asa_norte_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='distância até a Asa Norte (km)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['razao_social', 'nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('qualificacao', models.CharField(blank=True, max_length=100, verbose_name='qualificação')),
                ('faixa_etaria', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Não se aplica'), (1, '0 a 12 anos'), (2, '13 a 20 anos'), (3, '21 a 30 anos'), (4, '31 a 40 anos'), (5, '41 a 50 anos'), (6, '51 a 60 anos'), (7, '61 a 70 anos'), (8, '71 a 80 anos'), (9, 'Acima de 80 anos')], null=True, verbose_name='faixa etária')),
                ('data_entrada', models.DateField(blank=True, null=True, verbose_name='data de entrada')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'sócio',
                'verbose_name_plural': 'sócios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(max_length=2, verbose_name='DDD')),
                ('numero', models.CharField(max_length=9, verbose_name='número')),
                ('e164', models.CharField(help_text='Ex.: +5561999998888', max_length=14, verbose_name='número internacional')),
                ('eh_celular', models.BooleanField(default=False, verbose_name='é celular')),
                ('origem', models.CharField(choices=[('receita', 'Receita Federal'), ('csv', 'Planilha CSV'), ('google', 'Google'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'telefone',
                'verbose_name_plural': 'telefones',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'e164'), name='telefone_unico_por_empresa')],
            },
        ),
    ]
